CREATE TABLE SUBJECT
(
    SUB_SEQ     DECIMAL PRIMARY KEY,
    JAVA        VARCHAR2 (20),
    R           VARCHAR2 (20),
    SQL         VARCHAR2 (20),
    PYTHON      VARCHAR2 (20),
    HTML5       VARCHAR2 (20)
);

CREATE TABLE RECORD
(
    RECORD_SEQ  DECIMAL PRIMARY KEY,
    GRADE       VARCHAR2 (20),
    AVG         VARCHAR2 (20)
);
CREATE TABLE EXAM
(
    EXAM_SEQ    DECIMAL PRIMARY KEY,
    RECORD_SEQ  DECIMAL,
    SUB_SEQ     DECIMAL,
    MEM_ID      VARCHAR2 (20),
    MONTH       VARCHAR2 (20),
    SCORE       VARCHAR2 (20)
    
);
DROP TABLE EXAM;
alter table EXAM
ADD CONSTRAINT RECORD_SEQ_FK 
FOREIGN key (RECORD_SEQ) references RECORD(RECORD_SEQ);

ALTER TABLE EXAM
ADD CONSTRAINT SUB_SEQ_FK
FOREIGN KEY (SUB_SEQ) REFERENCES SUBJECT(SUB_SEQ);

ALTER TABLE EXAM
ADD CONSTRAINT MEM_ID_FK
FOREIGN KEY (MEM_ID) REFERENCES MEMBER(MEM_ID);