CREATE SEQUENCE SUB_SEQ;
CREATE TABLE SUBJECT
(
    SUB_SEQ     DECIMAL PRIMARY KEY,
    SUB_NAME    VARCHAR2 (20)
);

-- 苞格 眠啊
INSERT INTO SUBJECT VALUES (SUB_SEQ.NEXTVAL, 'JAVA');
INSERT INTO SUBJECT VALUES (SUB_SEQ.NEXTVAL, 'R');
INSERT INTO SUBJECT VALUES (SUB_SEQ.NEXTVAL, 'SQL');
INSERT INTO SUBJECT VALUES (SUB_SEQ.NEXTVAL, 'PYTHON');
INSERT INTO SUBJECT VALUES (SUB_SEQ.NEXTVAL, 'HTML5');

CREATE SEQUENCE RECORD_SEQ;
CREATE TABLE RECORD
(
    RECORD_SEQ  DECIMAL PRIMARY KEY,
    GRADE       VARCHAR2 (20),
    AVG         VARCHAR2 (20)
);

CREATE SEQUENCE EXAM_SEQ;
CREATE TABLE EXAM
(
    EXAM_SEQ    DECIMAL PRIMARY KEY,
    RECORD_SEQ  DECIMAL,
    SUB_SEQ     DECIMAL,
    MEM_ID      VARCHAR2 (20),
    MONTH       VARCHAR2 (20),
    SCORE       VARCHAR2 (20)
    
);
DROP TABLE EXAM;
alter table EXAM
ADD CONSTRAINT RECORD_SEQ_FK 
FOREIGN key (RECORD_SEQ) references RECORD(RECORD_SEQ);

ALTER TABLE EXAM
ADD CONSTRAINT SUB_SEQ_FK
FOREIGN KEY (SUB_SEQ) REFERENCES SUBJECT(SUB_SEQ);

ALTER TABLE EXAM
ADD CONSTRAINT MEM_ID_FK
FOREIGN KEY (MEM_ID) REFERENCES MEMBER(MEM_ID);



-- COLUMN 积己
ALTER TABLE SUBJECT
ADD (SUB_NAME VARCHAR2(20), SUB_TEST VARCHAR2(20));


-- COLUMN 昏力
ALTER TABLE SUBJECT 
DROP COLUMN PYTHON;